### ISSUE TITLE
Is this working with newest?

### ISSUE THREAD

**Issue by crotin1111** [BlueFrog130/Minecraft-KillCounter#1]
Should it work?

**Comment by BlueFrog130** [comment]
> Should it work?

@crotin1111  Yes, it should still work. But this will only work on Windows 10 with experimental features turned on.

Let me know if you want a version compatible with console and mobile

**Comment by crotin1111** [comment]
@BlueFrog130 of course I'd love for console, Xbox one to be specific,  that would be amazing mainly because I'm making a shop and the kill counter is important
One more thing
Is it possible to only set it up for all mobs except spider and creepers as I had to use command blocks to kill them. I'm an anxious person 🤣

**Comment by crotin1111** [comment]
@BlueFrog130 any news buddy?

**Comment by BlueFrog130** [comment]
Updated pack today. [Check it out](https://github.com/BlueFrog130/Minecraft-KillCounter/releases)

Should now work cross platform (I haven't been able to test it on Xbox, but it _should_ work on any platform).

Also added  a way for you to set up a custom tracker. In the future I will make some way to add multiple custom kill counters, but for now any player with tags of the name of the mob you want tracked will be tracked. Check out the [readme](https://github.com/BlueFrog130/Minecraft-KillCounter) for more info.

**Comment by crotin1111** [comment]
@BlueFrog130 could you make a tutorial if possible please, I have tried with no resulg. I maybe do it wrong

**Comment by crotin1111** [comment]
I have everything enabled so idk. Maybe it's because I have a realm but I use it with my girlfriend so

**Comment by BlueFrog130** [comment]
@crotin1111 What doesn't work? The mod? The scoreboard? The custom kill counter?

With the custom kill counter you need to use the full name of the entity when tagging the player. `/tag @s add minecraft:cow` for example will track cow kills in the `kc:custom` scoreboard objective. Make sure you use the full name of the mob in order to track it. To track sheep kills, you need `minecraft:sheep`

[Video of me tracking two different mobs](https://youtu.be/QNOK4p3l-6I)

**Comment by crotin1111** [comment]
For some reason I tried and I had to add it manually, I guess it's not for realms of anything sort, other than that I created a tag, created scoreboard for all mobs, all other add-ons I use have compatibilities and works all together, I assume it's a Minecraft bug or realm. Maybe it's a bug where it doesn't have a function for it but I don't know

**Comment by BlueFrog130** [comment]
For realms, I suppose you would need to manyally initialize the scoreboards. Since realms is always running, my _initialize_ function will never run when you add the mod. Therefore the only setup you need to do is add the `kc:all`, `kc:hostile`, and `kc:custom` scoreboard objectives and then everything should work.

**Comment by BlueFrog130** [comment]
There isn't some way for me to get scoreboard access via code, so I can't implement any checks to see if the scoreboard still needs initializing, my bad.

**Comment by BlueFrog130** [comment]
@crotin1111 I am also not sure if Realms allow for behavior packs with additional modding capabilities (a.k.a. run JavaScript code)

**Comment by crotin1111** [comment]
It does, I've been using add-ons for ages in realms and by far only two doesn't work
